swagger: '2.0'
info:
  title: goShop Api　
  description: goshop接口文档
  version: 1.0.0
host: 127.0.0.1:8099
schemes:
  - http
  - https
produces:
  - application/json

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization

security:
  - APIKeyHeader: []

paths:
