swagger: '2.0'
info:
  title: goShop Api　
  description: goshop接口文档
  version: 1.0.0
host: 10.32.5.88:8099
schemes:
  - http
  - https
produces:
  - application/json

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: goshop-token

security:
  - APIKeyHeader: []

paths:
